language: python

python: 3.6

branches: master

install:
    - pip install mkdocs mkdocs-material

script:
    - mkdocs build --verbose --clean --strict

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep-history: true
    local_dir: site
    target-branch: master
    on:
        branch: master