language: python
python: 3.6
cache: pip
branches: deploy
install:
    - pip install mkdocs mkdocs-material
script:
    - mkdocs build --verbose --clean --strict
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep-history: true
    local_dir: site
    target-branch: master
    on:
        branch: deploy