site_name: Ichor Official Website
site_description: Official Website for Ichor
site_url: https://ichor-rbx.github.io/
site_author: Kohl

edit_uri: "edit/deploy/docs"

theme:
    name: "material"
    custom_dir: "theme"
    logo: "assets/images/Ichor.png"
    favicon: "assets/images/Ichor.png"
    feature:
        tabs: true
    palette:
        primary: "grey"
        accent: "yellow"
extra_css:
    - stylesheets/dark_theme.css
    - stylesheets/codehilite.css

nav:
    - Introduction: index.md
    - Codex:
        - Overview: codex/overview.md
    - Credit: credit.md